# This file defines the data sources that dbt will use to pull data from Snowflake.
# In other words, it tells dbt where the original (raw) tables are located.
version: 2

sources:
  - name: raw_data
    database: finance_db    # Your Snowflake database
    schema: raw             # Schema where raw data is stored
    tables:
      - name: customers
      - name: orders
      - name: orders_items
      - name: products